channel_ids: 1441609159136116788,1441609139250921553
github:
    enabled: true
    owner: x2sw-tw
    repo: mcalts-logger
    token: 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
last_log:
    '1441609159136116788': '1441655987000967290'
user_token: MTQzODE2MzU0OTA4Mjg3Nzk4Mw.GEk09v.Avaeqb6CXz4KxaXZQ1PB6bWi6Vnbbhsm-JE8aM
